name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mdBook
        run: cargo install mdbook

      - name: Build cpp-book
        run: |
          cd cpp-book 
          mdbook build
          mkdir -p ../gh-pages
          cp -r book ../gh-pages/cpp-book

      - name: copy the root index file 
        run: |
          cp index.html ./gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
